### ISSUE TITLE
Question about implementation

### ISSUE THREAD

**Issue by k1ck3r** [AnneWielis/NetBoxUtils#1]
Hello,

i've found your plugins through Netbox's requested features, and i wonder if can give us advice how we can implement this power calculator in Netbox

**Comment by AnneWielis** [comment]
Sure, but my code is still on the 2.x netbox branch, we didn't upgrade by now.

Basically i just created a cron job calling some php code that loops all devices that have children (power sources, racks etc.) checks if a device contains child devices that carry a newer update date than its own. If so, it sums up the power load of those and manually enters it into the power field of the current device. Finally it updates the last updated field of the current device. Everything is done using a service user holding an api key. 

Not really nice but works for us and solved the recursion problem one would otherwise have. To be guarded against loops maximum depth is 5, i think.

Did that answer your question? 
Regards,
Anne

**Comment by k1ck3r** [comment]
Hey Anne,

thanks for your fast and prompt response, it's all clear now, thanks again
